services:
  mysql:
    build: ./mysql/
    container_name: ${MYSQL_URL}
    restart: always

    env_file:
      - .env

    ports:
      - "3306:${MYSQL_PORT}"

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - default_network
  frontend:
    build: ./react-app/
    container_name: ${FRONTEND_NAME}
    restart: always

    env_file:
      - .env

    volumes:
      - ./react-app/src:/app/src

    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      
    environment:
      CHOKIDAR_USEPOLLING: "true"

    networks:
      - default_network
  nginx:
    build: ./nginx/
    container_name: nginx
    restart: always

    env_file:
      - .env

    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"

    networks:
      - default_network
  discovery-service:
    build: ./discoveryService/
    container_name: ${DISCOVERY_SERVICE_NAME}
    restart: always

    env_file:
      - .env

    ports:
      - "${DISCOVERY_SERVICE_PORT}:${DISCOVERY_SERVICE_PORT}"

    volumes:
      - ./discoveryService:/app

    networks:
      - default_network
  gateway:
    build: ./gateway/
    container_name: ${GATEWAY_NAME}
    restart: always

    depends_on:
      - discovery-service

    env_file:
      - .env

    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

    volumes:
      - ./gateway:/app

    networks:
      - default_network
  authentication:
    build: ./authentication/
    container_name: ${AUTHENTICATION_NAME}
    restart: always

    depends_on:
      - mysql
      - gateway
      - discovery-service

    env_file:
      - .env

    ports:
      - "${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}"
    
    volumes:
      - ./authentication:/app

    networks:
      - default_network
  resource:
    build: ./resource/
    container_name: ${RESOURCE_NAME}
    restart: always

    extra_hosts:
      - "mysite.com:host-gateway"

    depends_on:
      - mysql
      - nginx
      - gateway
      - discovery-service
      - authentication

    env_file:
      - .env

    ports:
      - "${RESOURCE_PORT}:${RESOURCE_PORT}"

    volumes:
      - ./resource:/app

    networks:
      - default_network
  client:
    build: ./client/
    container_name: client
    restart: always

    extra_hosts:
      - "mysite.com:host-gateway"

    depends_on:
      - mysql
      - nginx
      - gateway
      - discovery-service
      - authentication

    env_file:
      - .env

    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

    volumes:
      - ./client:/app

    networks:
      - default_network
volumes:
  mysql_data:
    name: mysql_data

networks:
  default_network:
    driver: bridge
