logging:
  level:
    com.netflix.eureka: TRACE
    com.netflix.discovery: TRACE
    org.springframework.cloud.netflix.eureka: TRACE
    com.netflix.discovery.shared.MonitoredConnectionManager: TRACE
server:
  port: ${GATEWAY_PORT}
spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
  application:
    name: ${GATEWAY_NAME}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ${AUTHENTICATION_NAME}
              uri: lb://${AUTHENTICATION_NAME}
              predicates:
                - Path=/${AUTHENTICATION_NAME}/**
              preserve-host-header: true
            - id: ${RESOURCE_NAME}
              uri: lb://${RESOURCE_NAME}
              predicates:
                - Path=/${RESOURCE_NAME}/**
            - id: ${CLIENT_NAME}
              uri: lb://${CLIENT_NAME}
              predicates:
                - Path=/${CLIENT_NAME}/**
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}:${DISCOVERY_SERVICE_PORT}/eureka/
  instance:
    instanceId: ${spring.application.name}