logging:
  level:
    com.netflix.eureka: TRACE
    com.netflix.discovery: TRACE
    org.springframework.cloud.netflix.eureka: TRACE
    com.netflix.discovery.shared.MonitoredConnectionManager: TRACE
server:
  port: ${GATEWAY_PORT}
#  forward-headers-strategy: framework
spring:
#  webflux:
#    static-path-pattern: "/resources/**"
#  web:
#    resources:
#      static-locations: "classpath:/app/" # Custom directory
#      add-mappings: true # Ensure static resource handling is enabled
  application:
    name: ${GATEWAY_NAME}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ${AUTHENTICATION_NAME}
              uri: lb://${AUTHENTICATION_NAME}
              predicates:
                - Path=/${AUTHENTICATION_NAME}/**
              preserve-host-header: true
#              filters:
#                - StripPrefix=1
#              filters:
#                - StripPrefix=1
#              filters:
#                - name: SetRequestHeader
#                  args:
#                    name: X-Forwarded-Host
#                    value: http://mysite.com
#                - name: SetRequestHeader
#                  args:
#                    name: X-Forwarded-Proto
#                    value: http
            - id: ${RESOURCE_NAME}
              uri: lb://${RESOURCE_NAME}
              predicates:
                - Path=/${RESOURCE_NAME}/**
            - id: ${CLIENT_NAME}
              uri: lb://${CLIENT_NAME}
              predicates:
                - Path=/${CLIENT_NAME}/**
#            - id: spa-fallback
#              uri: forward:/index.html
#              predicates:
#                - Path=/login, /product
#                - Method=GET
eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL}:${DISCOVERY_SERVICE_PORT}/eureka/
  instance:
    instanceId: ${spring.application.name}